version: "3.8"

services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bluegreen-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 5

  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    networks:
      - bluegreen-net
    ports:
      - "80:80"
    volumes:
      # 1. On monte le dossier des configs 
      - ./nginx/conf.d:/etc/nginx/conf.d
      
      # 2. [IMPORTANT] On monte NOTRE nginx.conf pour écraser celui par défaut
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  bluegreen-net:
    external: true