version: "3.8"

services:
  reverse-proxy:
    build: ./nginx
    #container_name: reverse-proxy
    networks:
      - bluegreen-net
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

networks:
  bluegreen-net:
    external: true
