services:
  postgres:
    image: postgres:16
    #container_name: gym-postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - gym-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 2
      start_period: 5s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    #container_name: gym-backend
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT}:3000"
    networks:
      - gym-network
    command: sh -c "npx prisma migrate deploy && node src/index.js"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"] # Adjust port if different
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    #container_name: gym-frontend
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - gym-network
    healthcheck:
      # Nginx images usually don't have curl, so we use wget
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  gym-network:
    driver: bridge

# This top-level key is required to define the named volume
volumes:
  postgres_data: