global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gym-backend'
    metrics_path: /metrics
    static_configs:
      - targets:
          - gym-backend:3000  # container name of your backend
